### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Zimmi48** [chetmurthy/yayaml#1]
Hey! It looks like YAY is not provided under an explicit open source license. This means it cannot legally be used (especially not as a dependency for another project).

**Comment by chetmurthy** [comment]
ha!  I never thought anybody would even be interested in it.  If you are, I can add a license.  How would Apache sound ?

**Comment by Zimmi48** [comment]
Yes, we are interested in the context of https://github.com/coq-community/templates/issues/95. TBH, we do not know yet whether we will end up using YAY or ocaml-yaml. Apache 2.0 sounds perfectly fine.

**Comment by chetmurthy** [comment]
cool, I'll fix in a couple of hours (just waking up).  If you chose YAY, heck, I'd be happy to make improvements, while (of course) sticking to the design goals.

**Comment by chetmurthy** [comment]
Done.
